apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.mapbox.maps.token'
apply from: "${rootDir}/gradle/script-git-version.gradle"
apply from: "${rootDir}/gradle/ktlint.gradle"

android {
    namespace "com.mapbox.navigation.examples.aaos"
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId "com.mapbox.navigation.examples.aaos"
        minSdkVersion 29
        targetSdkVersion 36
        versionCode gitNumberOfCommits
        versionName gitTagDescription
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: 'true'
        vectorDrawables.useSupportLibrary = true
    }

    testOptions {
        execution 'ANDROIDX_TEST_ORCHESTRATOR'
    }

    buildTypes {
        debug {
            testCoverageEnabled = false
            manifestPlaceholders = [enableCrashReporting: "false"]
        }
        release {
            minifyEnabled true
            manifestPlaceholders = [enableCrashReporting: "true"]
        }
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    // Mapbox Navigation Android Auto SDK
    implementation("com.mapbox.navigationcore:android-ndk27:3.30.1")
    implementation("com.mapbox.navigationcore:android-auto-components-ndk27:3.30.1")

    // Android Automotive library
    // https://developer.android.com/jetpack/androidx/releases/car-app
    implementation("androidx.car.app:app:1.2.0")
    implementation("androidx.car.app:app-automotive:1.2.0")
}
